module.exports.BIGQUERY_TYPES = {
  'STRING': 'TEXT',
  'INTEGER': 'BIGINT',
  'INT64': 'BIGINT',
  'FLOAT': 'FLOAT',
  'FLOAT64': 'FLOAT',
  'NUMERIC': 'NUMERIC(38, 9)',
  'BOOLEAN': 'BOOLEAN',
  'BOOL': 'BOOLEAN',
  'DATE': 'DATE',
  'TIME': 'TIME',
  'DATETIME': 'TIMESTAMP WITH TIME ZONE'
};

module.exports.POSTGRES_TYPES = {
  'TEXT': 'STRING',
  'BIGINT': 'INTEGER',
  'BOOLEAN': 'BOOLEAN',
  'DOUBLE PRECISION': 'FLOAT',
  'TIME WITHOUT TIME ZONE': 'TIME',
  'DATE': 'DATE',
  'TIMESTAMP WITH TIME ZONE': 'DATETIME'
};
