version: "3.9"

services:
  app:
    image: not-so-bigquery
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    depends_on:
      - postgres
    environment:
      - NODE_ENV=development
      - PORT=8080
      - HOSTNAME=0.0.0.0
    command: ["ash", "-c", "npm run start:dev"]
    volumes:
      - ./:/code
      - /code/node_modules
    ports:
      - 5443:8080
    restart: always

  postgres:
    image: clkao/postgres-plv8:10-2
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/postgres/init_db:/docker-entrypoint-initdb.d
    ports:
      - 5532:5432
    command: ["postgres", "-c", "log_min_messages=INFO", "-c", "client_min_messages=LOG"]

volumes:
  db-data: ~
