version: '3.7'

services:
  app:
    image: not-so-bigquery
    build:
      context: .
    environment:
      - NODE_ENV=development
      - PORT=8080
      - HOSTNAME=0.0.0.0
    command: npm run start:dev
    volumes:
      - ./:/code
      - /code/node_modules
    ports:
      - 5443:8080
    restart: always

  postgres:
    image: clkao/postgres-plv8:10-2
    volumes:
      - ./tmp/postgres-not-so-bigquery/data:/var/lib/postgresql/data
      - ./docker/postgres/init_db:/docker-entrypoint-initdb.d
    ports:
      - 5532:5432
    environment:
      - POSTGRES_PASSWORD=password
