version: '3.7'

services:
  app:
    image: not-so-bigquery
    build:
      context: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: "8080"
      HTTPS: ~
      HOSTNAME: 0.0.0.0
      POSTGRES_HOST: 'postgres'
      POSTGRES_PORT: 5432
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    command: npm run start:dev
    volumes:
      - ./:/code
      - /code/node_modules
    ports:
      - 5443:8080

  postgres:
    image: postgres_15-plv8_3
    platform: linux/arm64
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.postgres
      shm_size: '4gb'
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/postgres/init_db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - 5532:5432
    command: ["postgres", "-c", "log_min_messages=NOTICE", "-c", "client_min_messages=NOTICE"]

volumes:
  db-data: ~
