version: '3.7'

services:
  app:
    image: not-so-bigquery
    build:
      context: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: "8080"
      HTTPS: ~
      HOSTNAME: 0.0.0.0
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: npm run start:dev
    volumes:
      - ./:/code
      - /code/node_modules
    ports:
      - 5443:8080
    restart: always

  postgres:
    image: clkao/postgres-plv8:10-2
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./docker/postgres/init_db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5532:5432
    command: ["postgres", "-c", "log_min_messages=DEBUG5", "-c", "client_min_messages=DEBUG5"]

volumes:
  db-data: ~
